import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PlayMusicButton from "./components/PlayMusicButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed left-4 bottom-4 sm:left-0 sm:bottom-[5%] sm:transform sm:translate-x-1/2 z-40">
          <PlayMusicButton />
        </div>
        {children}
      </body>
    </html>
  );
}